apiVersion: v1
kind: Secret
metadata:
  name: pong-board
  labels:
    app: pong-board
type: Opaque
data:
  database-url: "my base64 encoded database url postgres://USER:PASSWORD@HOST:PORT/NAME"
  cloudsql-instance: "my base64 encoded cloudsql instance project_id:region:instance_name"